VERMELHO = (217, 0, 0)
VERDE = (0, 153, 0)
AZUL = (0, 102, 255)
CORES_JOGO = [VERMELHO, VERDE, AZUL]

BRANCO = (255, 255, 255)
PRETO = (0, 0, 0)
CINZA_FUNDO = (30, 30, 30)

LARGURA = 800
ALTURA = 600

MENU = 0
JOGANDO = 1
GAME_OVER = 2

PLAYER_LARGURA = 40
PLAYER_ALTURA = 60
PLAYER_X_INICIAL = 100
PLAYER_Y_INICIAL = ALTURA - PLAYER_ALTURA - 100 

OBSTACULO_LARGURA_MIN = 30
OBSTACULO_LARGURA_MAX = 60
OBSTACULO_ALTURA_MIN = 50
OBSTACULO_ALTURA_MAX = 120
OBSTACULO_Y_POS = ALTURA - 50

ESCALA_PLAYER = 0.7
ESCALA_OBSTACULO = 0.3
ESCALA_BACKGROUND = 1.0

ESCALA_PORTAL_VERMELHO = 0.3
ESCALA_PORTAL_VERDE = 0.3
ESCALA_PORTAL_AZUL = 0.45  
ESCALAS_PORTAIS = [ESCALA_PORTAL_VERMELHO, ESCALA_PORTAL_VERDE, ESCALA_PORTAL_AZUL]  

VELOCIDADE_INICIAL_OBSTACULO = 250.0
ACELERACAO_VELOCIDADE = 1.05
FREQUENCIA_SPAWN_INICIAL = 2.0
REDUCAO_FREQUENCIA = 0.98 

ARQUIVO_FONTE = "Arial"
ARQUIVO_HIGH_SCORE = "highscore.txt"

AUDIO_MUDAR_COR = "audio/mudar_cor.mp3" 
AUDIO_FALHA = "audio/falha.mp3" 
AUDIO_RECORDE = "audio/recorde.mp3"

BACKGROUND = "assets/background.jpg"
BONECO_VERMELHO = "assets/boneco_vermelho.png"
BONECO_VERDE = "assets/boneco_verde.png"
BONECO_AZUL = "assets/boneco_azul.png"
BONECOS = [BONECO_VERMELHO, BONECO_VERDE, BONECO_AZUL]

PORTAL_VERMELHO = "assets/portal_vermelho.png"
PORTAL_VERDE = "assets/portal_verde.png"
PORTAL_AZUL = "assets/portal_azul.png"
PORTAIS = [PORTAL_VERMELHO, PORTAL_VERDE, PORTAL_AZUL]